export type McpCatalogEntry = {
  name: string
  category: string
  description: string
  icon: string
  popular?: boolean
  install_command: string
  env_vars?: string[]
}

export const MCP_CATALOG: McpCatalogEntry[] = [
  {
    name: 'GitHub',
    category: 'Development',
    description: 'Access repos, PRs, issues, and code',
    icon: '🐙',
    popular: true,
    install_command: 'npx -y @modelcontextprotocol/server-github',
    env_vars: ['GITHUB_TOKEN'],
  },
  {
    name: 'Supabase',
    category: 'Database',
    description: 'Query your Supabase database',
    icon: '⚡',
    popular: true,
    install_command: 'npx -y @modelcontextprotocol/server-postgres',
    env_vars: ['SUPABASE_URL', 'SUPABASE_KEY'],
  },
  {
    name: 'PostgreSQL',
    category: 'Database',
    description: 'Connect to PostgreSQL databases',
    icon: '🐘',
    popular: true,
    install_command: 'npx -y @modelcontextprotocol/server-postgres',
    env_vars: ['DATABASE_URL'],
  },
  {
    name: 'Filesystem',
    category: 'Storage',
    description: 'Read and write local files',
    icon: '📁',
    popular: true,
    install_command: 'npx -y @modelcontextprotocol/server-filesystem',
  },
  {
    name: 'Brave Search',
    category: 'Search',
    description: 'Search the web with Brave Search API',
    icon: '🦁',
    popular: true,
    install_command: 'npx -y @modelcontextprotocol/server-brave-search',
    env_vars: ['BRAVE_API_KEY'],
  },
  {
    name: 'Slack',
    category: 'Communication',
    description: 'Send messages and manage Slack channels',
    icon: '💬',
    install_command: 'npx -y @modelcontextprotocol/server-slack',
    env_vars: ['SLACK_BOT_TOKEN'],
  },
  {
    name: 'Google Drive',
    category: 'Storage',
    description: 'Access and manage Google Drive files',
    icon: '📂',
    install_command: 'npx -y @modelcontextprotocol/server-gdrive',
    env_vars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
  },
  {
    name: 'Notion',
    category: 'Productivity',
    description: 'Read and write Notion pages and databases',
    icon: '📝',
    install_command: 'npx -y @modelcontextprotocol/server-notion',
    env_vars: ['NOTION_API_KEY'],
  },
  {
    name: 'Puppeteer',
    category: 'Browser',
    description: 'Control a browser for web scraping',
    icon: '🤖',
    install_command: 'npx -y @modelcontextprotocol/server-puppeteer',
  },
  {
    name: 'SQLite',
    category: 'Database',
    description: 'Query and manage SQLite databases',
    icon: '🗃️',
    install_command: 'npx -y @modelcontextprotocol/server-sqlite',
  },
  {
    name: 'AWS KB Retrieval',
    category: 'Cloud',
    description: 'Retrieve from AWS Knowledge Base',
    icon: '☁️',
    install_command: 'npx -y @modelcontextprotocol/server-aws-kb-retrieval-server',
    env_vars: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'],
  },
  {
    name: 'Linear',
    category: 'Project Management',
    description: 'Manage Linear issues and projects',
    icon: '📐',
    install_command: 'npx -y @modelcontextprotocol/server-linear',
    env_vars: ['LINEAR_API_KEY'],
  },
  {
    name: 'Jira',
    category: 'Project Management',
    description: 'Access Jira issues and boards',
    icon: '🔵',
    install_command: 'npx -y @modelcontextprotocol/server-jira',
    env_vars: ['JIRA_URL', 'JIRA_API_TOKEN'],
  },
  {
    name: 'Figma',
    category: 'Design',
    description: 'Access Figma files and components',
    icon: '🎨',
    install_command: 'npx -y @modelcontextprotocol/server-figma',
    env_vars: ['FIGMA_TOKEN'],
  },
  {
    name: 'Stripe',
    category: 'Payments',
    description: 'Manage Stripe payments and customers',
    icon: '💳',
    install_command: 'npx -y @modelcontextprotocol/server-stripe',
    env_vars: ['STRIPE_SECRET_KEY'],
  },
  {
    name: 'Sentry',
    category: 'Monitoring',
    description: 'Track errors and performance issues',
    icon: '🚨',
    install_command: 'npx -y @modelcontextprotocol/server-sentry',
    env_vars: ['SENTRY_AUTH_TOKEN'],
  },
  {
    name: 'Vercel',
    category: 'Deployment',
    description: 'Manage Vercel deployments and projects',
    icon: '▲',
    install_command: 'npx -y @modelcontextprotocol/server-vercel',
    env_vars: ['VERCEL_TOKEN'],
  },
  {
    name: 'Docker',
    category: 'DevOps',
    description: 'Manage Docker containers and images',
    icon: '🐳',
    install_command: 'npx -y @modelcontextprotocol/server-docker',
  },
  {
    name: 'Kubernetes',
    category: 'DevOps',
    description: 'Manage Kubernetes clusters and pods',
    icon: '⚙️',
    install_command: 'npx -y @modelcontextprotocol/server-kubernetes',
    env_vars: ['KUBECONFIG'],
  },
  {
    name: 'OpenAI',
    category: 'AI/ML',
    description: 'Access OpenAI models and APIs',
    icon: '🧠',
    install_command: 'npx -y @modelcontextprotocol/server-openai',
    env_vars: ['OPENAI_API_KEY'],
  },
  {
    name: 'HuggingFace',
    category: 'AI/ML',
    description: 'Use HuggingFace models and datasets',
    icon: '🤗',
    install_command: 'npx -y @modelcontextprotocol/server-huggingface',
    env_vars: ['HF_TOKEN'],
  },
  {
    name: 'Pinecone',
    category: 'Vector DB',
    description: 'Query and upsert vector embeddings',
    icon: '🌲',
    install_command: 'npx -y @modelcontextprotocol/server-pinecone',
    env_vars: ['PINECONE_API_KEY'],
  },
  {
    name: 'Weaviate',
    category: 'Vector DB',
    description: 'Semantic search with Weaviate',
    icon: '🔮',
    install_command: 'npx -y @modelcontextprotocol/server-weaviate',
    env_vars: ['WEAVIATE_URL', 'WEAVIATE_API_KEY'],
  },
  {
    name: 'Airtable',
    category: 'Database',
    description: 'Access and update Airtable bases',
    icon: '📊',
    install_command: 'npx -y @modelcontextprotocol/server-airtable',
    env_vars: ['AIRTABLE_API_KEY'],
  },
  {
    name: 'Gmail',
    category: 'Communication',
    description: 'Read and send emails via Gmail',
    icon: '📧',
    install_command: 'npx -y @modelcontextprotocol/server-gmail',
    env_vars: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET'],
  },
]

export const MCP_CATEGORIES = Array.from(new Set(MCP_CATALOG.map((s) => s.category))).sort()
